# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

<<<<<<< HEAD
    The version of the OpenAPI document: 1.0.0
=======
    OpenAPI spec version: 1.0.0
>>>>>>> ooof
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import
<<<<<<< HEAD
import sys
=======

>>>>>>> ooof
import unittest

import petstore_api
from petstore_api.api.fake_classname_tags_123_api import FakeClassnameTags123Api  # noqa: E501
<<<<<<< HEAD
=======
from petstore_api.rest import ApiException
>>>>>>> ooof


class TestFakeClassnameTags123Api(unittest.TestCase):
    """FakeClassnameTags123Api unit test stubs"""

    def setUp(self):
<<<<<<< HEAD
        self.api = FakeClassnameTags123Api()  # noqa: E501
=======
        self.api = petstore_api.api.fake_classname_tags_123_api.FakeClassnameTags123Api()  # noqa: E501
>>>>>>> ooof

    def tearDown(self):
        pass

    def test_test_classname(self):
        """Test case for test_classname

        To test class name in snake case  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
