# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

<<<<<<< HEAD
    The version of the OpenAPI document: 1.0.0
=======
    OpenAPI spec version: 1.0.0
>>>>>>> ooof
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import
<<<<<<< HEAD
import sys
import unittest

import petstore_api
from petstore_api.model.additional_properties_object import AdditionalPropertiesObject
=======

import unittest

import petstore_api
from petstore_api.models.additional_properties_object import AdditionalPropertiesObject  # noqa: E501
from petstore_api.rest import ApiException
from petstore_api.exceptions import ApiTypeError

import datetime
>>>>>>> ooof


class TestAdditionalPropertiesObject(unittest.TestCase):
    """AdditionalPropertiesObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdditionalPropertiesObject(self):
        """Test AdditionalPropertiesObject"""
        # can make model without additional properties
        model = AdditionalPropertiesObject()

        # can make one with additional properties
        some_val = {}
        model = AdditionalPropertiesObject(some_key=some_val)
        assert model['some_key'] == some_val
<<<<<<< HEAD
        import datetime
=======
>>>>>>> ooof
        some_val = {'a': True, 'b': datetime.date(1970,1,1), 'c': datetime.datetime(1970,1,1), 'd': {}, 'e': 3.1, 'f': 1, 'g': [], 'h': 'hello'}
        model = AdditionalPropertiesObject(some_key=some_val)
        assert model['some_key'] == some_val

        # type checking works on additional properties
<<<<<<< HEAD
        with self.assertRaises(petstore_api.ApiTypeError) as exc:
=======
        with self.assertRaises(ApiTypeError) as exc:
>>>>>>> ooof
            model = AdditionalPropertiesObject(some_key='some string')


if __name__ == '__main__':
    unittest.main()
