//
// DogAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct DogAllOf: Codable { 

=======
public struct DogAllOf: Codable {
>>>>>>> ooof

    public var breed: String?

    public init(breed: String?) {
        self.breed = breed
    }

}
