//
// MixedPropertiesAndAdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct MixedPropertiesAndAdditionalPropertiesClass: Codable { 


    public var uuid: UUID?
    public var dateTime: Date?
    public var map: [String:Animal]?

    public init(uuid: UUID?, dateTime: Date?, map: [String:Animal]?) {
=======
public struct MixedPropertiesAndAdditionalPropertiesClass: Codable {

    public var uuid: UUID?
    public var dateTime: Date?
    public var map: [String: Animal]?

    public init(uuid: UUID?, dateTime: Date?, map: [String: Animal]?) {
>>>>>>> ooof
        self.uuid = uuid
        self.dateTime = dateTime
        self.map = map
    }

}
