//
// NumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct NumberOnly: Codable { 

=======
public struct NumberOnly: Codable {
>>>>>>> ooof

    public var justNumber: Double?

    public init(justNumber: Double?) {
        self.justNumber = justNumber
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case justNumber = "JustNumber"
    }

}
