/**
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
<<<<<<< HEAD
 * OpenAPI spec version: 1.0.0
=======
 * The version of the OpenAPI document: 1.0.0
>>>>>>> ooof
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TypeHolderExample model module.
 * @module model/TypeHolderExample
 * @version 1.0.0
 */
class TypeHolderExample {
    /**
     * Constructs a new <code>TypeHolderExample</code>.
     * @alias module:model/TypeHolderExample
     * @param stringItem {String} 
     * @param numberItem {Number} 
<<<<<<< HEAD
=======
     * @param floatItem {Number} 
>>>>>>> ooof
     * @param integerItem {Number} 
     * @param boolItem {Boolean} 
     * @param arrayItem {Array.<Number>} 
     */
<<<<<<< HEAD
    constructor(stringItem, numberItem, integerItem, boolItem, arrayItem) { 
        
        TypeHolderExample.initialize(this, stringItem, numberItem, integerItem, boolItem, arrayItem);
=======
    constructor(stringItem, numberItem, floatItem, integerItem, boolItem, arrayItem) { 
        
        TypeHolderExample.initialize(this, stringItem, numberItem, floatItem, integerItem, boolItem, arrayItem);
>>>>>>> ooof
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
<<<<<<< HEAD
    static initialize(obj, stringItem, numberItem, integerItem, boolItem, arrayItem) { 
        obj['string_item'] = stringItem;
        obj['number_item'] = numberItem;
=======
    static initialize(obj, stringItem, numberItem, floatItem, integerItem, boolItem, arrayItem) { 
        obj['string_item'] = stringItem;
        obj['number_item'] = numberItem;
        obj['float_item'] = floatItem;
>>>>>>> ooof
        obj['integer_item'] = integerItem;
        obj['bool_item'] = boolItem;
        obj['array_item'] = arrayItem;
    }

    /**
     * Constructs a <code>TypeHolderExample</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TypeHolderExample} obj Optional instance to populate.
     * @return {module:model/TypeHolderExample} The populated <code>TypeHolderExample</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypeHolderExample();

            if (data.hasOwnProperty('string_item')) {
                obj['string_item'] = ApiClient.convertToType(data['string_item'], 'String');
            }
            if (data.hasOwnProperty('number_item')) {
                obj['number_item'] = ApiClient.convertToType(data['number_item'], 'Number');
            }
<<<<<<< HEAD
=======
            if (data.hasOwnProperty('float_item')) {
                obj['float_item'] = ApiClient.convertToType(data['float_item'], 'Number');
            }
>>>>>>> ooof
            if (data.hasOwnProperty('integer_item')) {
                obj['integer_item'] = ApiClient.convertToType(data['integer_item'], 'Number');
            }
            if (data.hasOwnProperty('bool_item')) {
                obj['bool_item'] = ApiClient.convertToType(data['bool_item'], 'Boolean');
            }
            if (data.hasOwnProperty('array_item')) {
                obj['array_item'] = ApiClient.convertToType(data['array_item'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} string_item
 */
TypeHolderExample.prototype['string_item'] = undefined;

/**
 * @member {Number} number_item
 */
TypeHolderExample.prototype['number_item'] = undefined;

/**
<<<<<<< HEAD
=======
 * @member {Number} float_item
 */
TypeHolderExample.prototype['float_item'] = undefined;

/**
>>>>>>> ooof
 * @member {Number} integer_item
 */
TypeHolderExample.prototype['integer_item'] = undefined;

/**
 * @member {Boolean} bool_item
 */
TypeHolderExample.prototype['bool_item'] = undefined;

/**
 * @member {Array.<Number>} array_item
 */
TypeHolderExample.prototype['array_item'] = undefined;






export default TypeHolderExample;

