//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct Tag: Codable { 

=======
public struct Tag: Codable {
>>>>>>> ooof

    public var id: Int64?
    public var name: String?

    public init(id: Int64?, name: String?) {
        self.id = id
        self.name = name
    }

}
