//
// Client.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct Client: Codable { 

=======
public struct Client: Codable {
>>>>>>> ooof

    public var client: String?

    public init(client: String?) {
        self.client = client
    }

}
