<?php
/**
 * EnumTestTest
 *
<<<<<<< HEAD
 * PHP version 7.2
=======
 * PHP version 7.1
>>>>>>> ooof
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * EnumTestTest Class Doc Comment
 *
 * @category    Class
 * @description EnumTest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EnumTestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
<<<<<<< HEAD
    public static function setUpBeforeClass(): void
=======
    public static function setUpBeforeClass()
>>>>>>> ooof
    {
    }

    /**
     * Setup before running each test case
     */
<<<<<<< HEAD
    public function setUp(): void
=======
    public function setUp()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running each test case
     */
<<<<<<< HEAD
    public function tearDown(): void
=======
    public function tearDown()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running all test cases
     */
<<<<<<< HEAD
    public static function tearDownAfterClass(): void
=======
    public static function tearDownAfterClass()
>>>>>>> ooof
    {
    }

    /**
     * Test "EnumTest"
     */
    public function testEnumTest()
    {
    }

    /**
     * Test attribute "enum_string"
     */
    public function testPropertyEnumString()
    {
    }

    /**
     * Test attribute "enum_string_required"
     */
    public function testPropertyEnumStringRequired()
    {
    }

    /**
     * Test attribute "enum_integer"
     */
    public function testPropertyEnumInteger()
    {
    }

    /**
     * Test attribute "enum_number"
     */
    public function testPropertyEnumNumber()
    {
    }

    /**
     * Test attribute "outer_enum"
     */
    public function testPropertyOuterEnum()
    {
    }
<<<<<<< HEAD

    /**
     * Test attribute "outer_enum_integer"
     */
    public function testPropertyOuterEnumInteger()
    {
    }

    /**
     * Test attribute "outer_enum_default_value"
     */
    public function testPropertyOuterEnumDefaultValue()
    {
    }

    /**
     * Test attribute "outer_enum_integer_default_value"
     */
    public function testPropertyOuterEnumIntegerDefaultValue()
    {
    }
=======
>>>>>>> ooof
}
