<?php
/**
 * FormatTestTest
 *
<<<<<<< HEAD
 * PHP version 7.2
=======
 * PHP version 7.1
>>>>>>> ooof
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * FormatTestTest Class Doc Comment
 *
 * @category    Class
 * @description FormatTest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FormatTestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
<<<<<<< HEAD
    public static function setUpBeforeClass(): void
=======
    public static function setUpBeforeClass()
>>>>>>> ooof
    {
    }

    /**
     * Setup before running each test case
     */
<<<<<<< HEAD
    public function setUp(): void
=======
    public function setUp()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running each test case
     */
<<<<<<< HEAD
    public function tearDown(): void
=======
    public function tearDown()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running all test cases
     */
<<<<<<< HEAD
    public static function tearDownAfterClass(): void
=======
    public static function tearDownAfterClass()
>>>>>>> ooof
    {
    }

    /**
     * Test "FormatTest"
     */
    public function testFormatTest()
    {
    }

    /**
     * Test attribute "integer"
     */
    public function testPropertyInteger()
    {
    }

    /**
     * Test attribute "int32"
     */
    public function testPropertyInt32()
    {
    }

    /**
     * Test attribute "int64"
     */
    public function testPropertyInt64()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "float"
     */
    public function testPropertyFloat()
    {
    }

    /**
     * Test attribute "double"
     */
    public function testPropertyDouble()
    {
    }

    /**
     * Test attribute "string"
     */
    public function testPropertyString()
    {
    }

    /**
     * Test attribute "byte"
     */
    public function testPropertyByte()
    {
    }

    /**
     * Test attribute "binary"
     */
    public function testPropertyBinary()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "date_time"
     */
    public function testPropertyDateTime()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
<<<<<<< HEAD
     * Test attribute "pattern_with_digits"
     */
    public function testPropertyPatternWithDigits()
    {
    }

    /**
     * Test attribute "pattern_with_digits_and_delimiter"
     */
    public function testPropertyPatternWithDigitsAndDelimiter()
=======
     * Test attribute "big_decimal"
     */
    public function testPropertyBigDecimal()
>>>>>>> ooof
    {
    }
}
