<?php

/**
<<<<<<< HEAD
 * OpenAPI Petstore
 * PHP version 7.2
 *
 * @package OpenAPIServer
=======
 * StoreApiTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
>>>>>>> ooof
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
<<<<<<< HEAD
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
=======
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
>>>>>>> ooof
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\StoreApi;

/**
 * StoreApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\StoreApi
 */
class StoreApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
<<<<<<< HEAD
    public static function setUpBeforeClass(): void
=======
    public static function setUpBeforeClass()
>>>>>>> ooof
    {
    }

    /**
     * Setup before running each test case
     */
<<<<<<< HEAD
    public function setUp(): void
=======
    public function setUp()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running each test case
     */
<<<<<<< HEAD
    public function tearDown(): void
=======
    public function tearDown()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running all test cases
     */
<<<<<<< HEAD
    public static function tearDownAfterClass(): void
=======
    public static function tearDownAfterClass()
>>>>>>> ooof
    {
    }

    /**
     * Test case for deleteOrder
     *
     * Delete purchase order by ID.
     *
     * @covers ::deleteOrder
     */
    public function testDeleteOrder()
    {
<<<<<<< HEAD
        $this->markTestIncomplete(
            'Test of "deleteOrder" method has not been implemented yet.'
        );
=======
>>>>>>> ooof
    }

    /**
     * Test case for getInventory
     *
     * Returns pet inventories by status.
     *
     * @covers ::getInventory
     */
    public function testGetInventory()
    {
<<<<<<< HEAD
        $this->markTestIncomplete(
            'Test of "getInventory" method has not been implemented yet.'
        );
=======
>>>>>>> ooof
    }

    /**
     * Test case for getOrderById
     *
     * Find purchase order by ID.
     *
     * @covers ::getOrderById
     */
    public function testGetOrderById()
    {
<<<<<<< HEAD
        $this->markTestIncomplete(
            'Test of "getOrderById" method has not been implemented yet.'
        );
=======
>>>>>>> ooof
    }

    /**
     * Test case for placeOrder
     *
     * Place an order for a pet.
     *
     * @covers ::placeOrder
     */
    public function testPlaceOrder()
    {
<<<<<<< HEAD
        $this->markTestIncomplete(
            'Test of "placeOrder" method has not been implemented yet.'
        );
=======
>>>>>>> ooof
    }
}
