//! Main binary entry point for petstore_with_fake_endpoints_models_for_testing implementation.

#![allow(missing_docs)]

use clap::{App, Arg};

mod server;


/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
<<<<<<< HEAD
#[tokio::main]
async fn main() {
=======
fn main() {
>>>>>>> ooof
    env_logger::init();

    let matches = App::new("server")
        .arg(Arg::with_name("https")
            .long("https")
            .help("Whether to use HTTPS or not"))
        .get_matches();

    let addr = "127.0.0.1:80";

<<<<<<< HEAD
    server::create(addr, matches.is_present("https")).await;
=======
    hyper::rt::run(server::create(addr, matches.is_present("https")));
>>>>>>> ooof
}
