<?php
/**
 * FakeApiTest
<<<<<<< HEAD
 * PHP version 7.2
=======
 * PHP version 7.1
>>>>>>> ooof
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FakeApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FakeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
<<<<<<< HEAD
    public static function setUpBeforeClass(): void
=======
    public static function setUpBeforeClass()
>>>>>>> ooof
    {
    }

    /**
     * Setup before running each test case
     */
<<<<<<< HEAD
    public function setUp(): void
=======
    public function setUp()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running each test case
     */
<<<<<<< HEAD
    public function tearDown(): void
=======
    public function tearDown()
>>>>>>> ooof
    {
    }

    /**
     * Clean up after running all test cases
     */
<<<<<<< HEAD
    public static function tearDownAfterClass(): void
=======
    public static function tearDownAfterClass()
>>>>>>> ooof
    {
    }

    /**
<<<<<<< HEAD
     * Test case for fakeHealthGet
     *
     * Health check endpoint.
     *
     */
    public function testFakeHealthGet()
    {
    }

    /**
     * Test case for fakeHttpSignatureTest
     *
     * test http signature authentication.
     *
     */
    public function testFakeHttpSignatureTest()
=======
     * Test case for createXmlItem
     *
     * creates an XmlItem.
     *
     */
    public function testCreateXmlItem()
>>>>>>> ooof
    {
    }

    /**
     * Test case for fakeOuterBooleanSerialize
     *
     * .
     *
     */
    public function testFakeOuterBooleanSerialize()
    {
    }

    /**
     * Test case for fakeOuterCompositeSerialize
     *
     * .
     *
     */
    public function testFakeOuterCompositeSerialize()
    {
    }

    /**
     * Test case for fakeOuterNumberSerialize
     *
     * .
     *
     */
    public function testFakeOuterNumberSerialize()
    {
    }

    /**
     * Test case for fakeOuterStringSerialize
     *
     * .
     *
     */
    public function testFakeOuterStringSerialize()
    {
    }

    /**
     * Test case for testBodyWithFileSchema
     *
     * .
     *
     */
    public function testTestBodyWithFileSchema()
    {
    }

    /**
     * Test case for testBodyWithQueryParams
     *
     * .
     *
     */
    public function testTestBodyWithQueryParams()
    {
    }

    /**
     * Test case for testClientModel
     *
     * To test \"client\" model.
     *
     */
    public function testTestClientModel()
    {
    }

    /**
     * Test case for testEndpointParameters
     *
<<<<<<< HEAD
     * Fake endpoint for testing various parameters 假端點 偽のエンドポイント 가짜 엔드 포인트.
=======
     * Fake endpoint for testing various parameters  假端點  偽のエンドポイント  가짜 엔드 포인트.
>>>>>>> ooof
     *
     */
    public function testTestEndpointParameters()
    {
    }

    /**
     * Test case for testEnumParameters
     *
     * To test enum parameters.
     *
     */
    public function testTestEnumParameters()
    {
    }

    /**
     * Test case for testGroupParameters
     *
     * Fake endpoint to test group parameters (optional).
     *
     */
    public function testTestGroupParameters()
    {
    }

    /**
     * Test case for testInlineAdditionalProperties
     *
     * test inline additionalProperties.
     *
     */
    public function testTestInlineAdditionalProperties()
    {
    }

    /**
     * Test case for testJsonFormData
     *
     * test json serialization of form data.
     *
     */
    public function testTestJsonFormData()
    {
    }

    /**
     * Test case for testQueryParameterCollectionFormat
     *
     * .
     *
     */
    public function testTestQueryParameterCollectionFormat()
    {
    }
}
