//
// FileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct FileSchemaTestClass: Codable { 

=======
public struct FileSchemaTestClass: Codable {
>>>>>>> ooof

    public var file: File?
    public var files: [File]?

    public init(file: File?, files: [File]?) {
        self.file = file
        self.files = files
    }

}
