//
// Return.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing reserved words */
<<<<<<< HEAD
public struct Return: Codable { 

=======
public struct Return: Codable {
>>>>>>> ooof

    public var _return: Int?

    public init(_return: Int?) {
        self._return = _return
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _return = "return"
    }

}
