//
// ArrayOfNumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct ArrayOfNumberOnly: Codable { 

=======
internal struct ArrayOfNumberOnly: Codable {
>>>>>>> ooof

    internal var arrayNumber: [Double]?

    internal init(arrayNumber: [Double]?) {
        self.arrayNumber = arrayNumber
    }

<<<<<<< HEAD
    internal enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    internal enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case arrayNumber = "ArrayNumber"
    }

}
