//
// ArrayOfArrayOfNumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct ArrayOfArrayOfNumberOnly: Codable { 

=======
internal struct ArrayOfArrayOfNumberOnly: Codable {
>>>>>>> ooof

    internal var arrayArrayNumber: [[Double]]?

    internal init(arrayArrayNumber: [[Double]]?) {
        self.arrayArrayNumber = arrayArrayNumber
    }

<<<<<<< HEAD
    internal enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    internal enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case arrayArrayNumber = "ArrayArrayNumber"
    }

}
