//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct Cat: Codable { 

=======
internal struct Cat: Codable {
>>>>>>> ooof

    internal var className: String
    internal var color: String? = "red"
    internal var declawed: Bool?

    internal init(className: String, color: String?, declawed: Bool?) {
        self.className = className
        self.color = color
        self.declawed = declawed
    }

}
