//
// CatAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct CatAllOf: Codable { 

=======
internal struct CatAllOf: Codable {
>>>>>>> ooof

    internal var declawed: Bool?

    internal init(declawed: Bool?) {
        self.declawed = declawed
    }

}
