//
// ClassModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing model with \&quot;_class\&quot; property */
<<<<<<< HEAD
internal struct ClassModel: Codable { 

=======
internal struct ClassModel: Codable {
>>>>>>> ooof

    internal var _class: String?

    internal init(_class: String?) {
        self._class = _class
    }

}
