//
// Client.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct Client: Codable { 

=======
internal struct Client: Codable {
>>>>>>> ooof

    internal var client: String?

    internal init(client: String?) {
        self.client = client
    }

}
