//
// Dog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct Dog: Codable { 

=======
internal struct Dog: Codable {
>>>>>>> ooof

    internal var className: String
    internal var color: String? = "red"
    internal var breed: String?

    internal init(className: String, color: String?, breed: String?) {
        self.className = className
        self.color = color
        self.breed = breed
    }

}
