//
// EnumClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

=======
>>>>>>> ooof
internal enum EnumClass: String, Codable, CaseIterable {
    case abc = "_abc"
    case efg = "-efg"
    case xyz = "(xyz)"
}
