//
// File.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Must be named &#x60;File&#x60; for test. */
<<<<<<< HEAD
internal struct File: Codable { 

=======
internal struct File: Codable {
>>>>>>> ooof

    /** Test capitalization */
    internal var sourceURI: String?

    internal init(sourceURI: String?) {
        self.sourceURI = sourceURI
    }

}
