//
// FileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct FileSchemaTestClass: Codable { 

=======
internal struct FileSchemaTestClass: Codable {
>>>>>>> ooof

    internal var file: File?
    internal var files: [File]?

    internal init(file: File?, files: [File]?) {
        self.file = file
        self.files = files
    }

}
