//
// HasOnlyReadOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct HasOnlyReadOnly: Codable { 

=======
internal struct HasOnlyReadOnly: Codable {
>>>>>>> ooof

    internal var bar: String?
    internal var foo: String?

    internal init(bar: String?, foo: String?) {
        self.bar = bar
        self.foo = foo
    }

}
