//
// List.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct List: Codable { 

=======
internal struct List: Codable {
>>>>>>> ooof

    internal var _123list: String?

    internal init(_123list: String?) {
        self._123list = _123list
    }

<<<<<<< HEAD
    internal enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    internal enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _123list = "123-list"
    }

}
