//
// Name.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing model name same as property name */
<<<<<<< HEAD
internal struct Name: Codable { 

=======
internal struct Name: Codable {
>>>>>>> ooof

    internal var name: Int
    internal var snakeCase: Int?
    internal var property: String?
    internal var _123number: Int?

    internal init(name: Int, snakeCase: Int?, property: String?, _123number: Int?) {
        self.name = name
        self.snakeCase = snakeCase
        self.property = property
        self._123number = _123number
    }

<<<<<<< HEAD
    internal enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    internal enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case name
        case snakeCase = "snake_case"
        case property
        case _123number = "123Number"
    }

}
