//
// OuterComposite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct OuterComposite: Codable { 

=======
internal struct OuterComposite: Codable {
>>>>>>> ooof

    internal var myNumber: Double?
    internal var myString: String?
    internal var myBoolean: Bool?

    internal init(myNumber: Double?, myString: String?, myBoolean: Bool?) {
        self.myNumber = myNumber
        self.myString = myString
        self.myBoolean = myBoolean
    }

<<<<<<< HEAD
    internal enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    internal enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case myNumber = "my_number"
        case myString = "my_string"
        case myBoolean = "my_boolean"
    }

}
