//
// OuterEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

=======
>>>>>>> ooof
internal enum OuterEnum: String, Codable, CaseIterable {
    case placed = "placed"
    case approved = "approved"
    case delivered = "delivered"
}
