//
// ReadOnlyFirst.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct ReadOnlyFirst: Codable { 

=======
internal struct ReadOnlyFirst: Codable {
>>>>>>> ooof

    internal var bar: String?
    internal var baz: String?

    internal init(bar: String?, baz: String?) {
        self.bar = bar
        self.baz = baz
    }

}
