//
// Return.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing reserved words */
<<<<<<< HEAD
internal struct Return: Codable { 

=======
internal struct Return: Codable {
>>>>>>> ooof

    internal var _return: Int?

    internal init(_return: Int?) {
        self._return = _return
    }

<<<<<<< HEAD
    internal enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    internal enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _return = "return"
    }

}
