//
// SpecialModelName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct SpecialModelName: Codable { 

=======
internal struct SpecialModelName: Codable {
>>>>>>> ooof

    internal var specialPropertyName: Int64?

    internal init(specialPropertyName: Int64?) {
        self.specialPropertyName = specialPropertyName
    }

<<<<<<< HEAD
    internal enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    internal enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case specialPropertyName = "$special[property.name]"
    }

}
