//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

internal struct Tag: Codable { 

=======
internal struct Tag: Codable {
>>>>>>> ooof

    internal var id: Int64?
    internal var name: String?

    internal init(id: Int64?, name: String?) {
        self.id = id
        self.name = name
    }

}
