//
// Animal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class Animal: NSObject, Codable { 
=======
@objc public class Animal: NSObject, Codable {
>>>>>>> ooof

    public var _className: String
    public var color: String? = "red"

    public init(_className: String, color: String?) {
        self._className = _className
        self.color = color
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _className = "className"
        case color
    }

}
