//
// ApiResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class ApiResponse: NSObject, Codable { 
=======
@objc public class ApiResponse: NSObject, Codable {
>>>>>>> ooof

    public var code: Int?
    public var codeNum: NSNumber? {
        get {
            return code as NSNumber?
        }
    }
    public var type: String?
    public var message: String?

    public init(code: Int?, type: String?, message: String?) {
        self.code = code
        self.type = type
        self.message = message
    }

}
