//
// ArrayOfArrayOfNumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class ArrayOfArrayOfNumberOnly: NSObject, Codable { 
=======
@objc public class ArrayOfArrayOfNumberOnly: NSObject, Codable {
>>>>>>> ooof

    public var arrayArrayNumber: [[Double]]?

    public init(arrayArrayNumber: [[Double]]?) {
        self.arrayArrayNumber = arrayArrayNumber
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case arrayArrayNumber = "ArrayArrayNumber"
    }

}
