//
// ArrayOfNumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class ArrayOfNumberOnly: NSObject, Codable { 
=======
@objc public class ArrayOfNumberOnly: NSObject, Codable {
>>>>>>> ooof

    public var arrayNumber: [Double]?

    public init(arrayNumber: [Double]?) {
        self.arrayNumber = arrayNumber
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case arrayNumber = "ArrayNumber"
    }

}
