//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class Cat: NSObject, Codable { 
=======
@objc public class Cat: NSObject, Codable {
>>>>>>> ooof

    public var _className: String
    public var color: String? = "red"
    public var declawed: Bool?
    public var declawedNum: NSNumber? {
        get {
            return declawed as NSNumber?
        }
    }

    public init(_className: String, color: String?, declawed: Bool?) {
        self._className = _className
        self.color = color
        self.declawed = declawed
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _className = "className"
        case color
        case declawed
    }

}
