//
// CatAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class CatAllOf: NSObject, Codable { 
=======
@objc public class CatAllOf: NSObject, Codable {
>>>>>>> ooof

    public var declawed: Bool?
    public var declawedNum: NSNumber? {
        get {
            return declawed as NSNumber?
        }
    }

    public init(declawed: Bool?) {
        self.declawed = declawed
    }

}
