//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class Category: NSObject, Codable { 
=======
@objc public class Category: NSObject, Codable {
>>>>>>> ooof

    public var _id: Int64?
    public var _idNum: NSNumber? {
        get {
            return _id as NSNumber?
        }
    }
    public var name: String = "default-name"

    public init(_id: Int64?, name: String) {
        self._id = _id
        self.name = name
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _id = "id"
        case name
    }

}
