//
// ClassModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing model with \&quot;_class\&quot; property */

<<<<<<< HEAD
@objc public class ClassModel: NSObject, Codable { 
=======
@objc public class ClassModel: NSObject, Codable {
>>>>>>> ooof

    public var _class: String?

    public init(_class: String?) {
        self._class = _class
    }

}
