//
// Client.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class Client: NSObject, Codable { 
=======
@objc public class Client: NSObject, Codable {
>>>>>>> ooof

    public var client: String?

    public init(client: String?) {
        self.client = client
    }

}
