//
// Dog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class Dog: NSObject, Codable { 
=======
@objc public class Dog: NSObject, Codable {
>>>>>>> ooof

    public var _className: String
    public var color: String? = "red"
    public var breed: String?

    public init(_className: String, color: String?, breed: String?) {
        self._className = _className
        self.color = color
        self.breed = breed
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _className = "className"
        case color
        case breed
    }

}
