//
// File.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Must be named &#x60;File&#x60; for test. */

<<<<<<< HEAD
@objc public class File: NSObject, Codable { 
=======
@objc public class File: NSObject, Codable {
>>>>>>> ooof

    /** Test capitalization */
    public var sourceURI: String?

    public init(sourceURI: String?) {
        self.sourceURI = sourceURI
    }

}
