//
// FileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class FileSchemaTestClass: NSObject, Codable { 
=======
@objc public class FileSchemaTestClass: NSObject, Codable {
>>>>>>> ooof

    public var file: File?
    public var files: [File]?

    public init(file: File?, files: [File]?) {
        self.file = file
        self.files = files
    }

}
