//
// HasOnlyReadOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class HasOnlyReadOnly: NSObject, Codable { 
=======
@objc public class HasOnlyReadOnly: NSObject, Codable {
>>>>>>> ooof

    public var bar: String?
    public var foo: String?

    public init(bar: String?, foo: String?) {
        self.bar = bar
        self.foo = foo
    }

}
