//
// Model200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing model name starting with number */

<<<<<<< HEAD
@objc public class Model200Response: NSObject, Codable { 
=======
@objc public class Model200Response: NSObject, Codable {
>>>>>>> ooof

    public var name: Int?
    public var nameNum: NSNumber? {
        get {
            return name as NSNumber?
        }
    }
    public var _class: String?

    public init(name: Int?, _class: String?) {
        self.name = name
        self._class = _class
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case name
        case _class = "class"
    }

}
