//
// OuterComposite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class OuterComposite: NSObject, Codable { 
=======
@objc public class OuterComposite: NSObject, Codable {
>>>>>>> ooof

    public var myNumber: Double?
    public var myString: String?
    public var myBoolean: Bool?
    public var myBooleanNum: NSNumber? {
        get {
            return myBoolean as NSNumber?
        }
    }

    public init(myNumber: Double?, myString: String?, myBoolean: Bool?) {
        self.myNumber = myNumber
        self.myString = myString
        self.myBoolean = myBoolean
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case myNumber = "my_number"
        case myString = "my_string"
        case myBoolean = "my_boolean"
    }

}
