//
// ReadOnlyFirst.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class ReadOnlyFirst: NSObject, Codable { 
=======
@objc public class ReadOnlyFirst: NSObject, Codable {
>>>>>>> ooof

    public var bar: String?
    public var baz: String?

    public init(bar: String?, baz: String?) {
        self.bar = bar
        self.baz = baz
    }

}
