//
// Return.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing reserved words */

<<<<<<< HEAD
@objc public class Return: NSObject, Codable { 
=======
@objc public class Return: NSObject, Codable {
>>>>>>> ooof

    public var _return: Int?
    public var _returnNum: NSNumber? {
        get {
            return _return as NSNumber?
        }
    }

    public init(_return: Int?) {
        self._return = _return
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _return = "return"
    }

}
