//
// SpecialModelName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD


@objc public class SpecialModelName: NSObject, Codable { 
=======
@objc public class SpecialModelName: NSObject, Codable {
>>>>>>> ooof

    public var specialPropertyName: Int64?
    public var specialPropertyNameNum: NSNumber? {
        get {
            return specialPropertyName as NSNumber?
        }
    }

    public init(specialPropertyName: Int64?) {
        self.specialPropertyName = specialPropertyName
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case specialPropertyName = "$special[property.name]"
    }

}
