<?php

/**
<<<<<<< HEAD
 * OpenAPI Petstore
 * PHP version 7.2
 *
 * @package OpenAPIServer
=======
 * Pet
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
>>>>>>> ooof
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
<<<<<<< HEAD
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
=======
>>>>>>> ooof
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

<<<<<<< HEAD
use OpenAPIServer\BaseModel;
=======
use OpenAPIServer\Interfaces\ModelInterface;
>>>>>>> ooof

/**
 * Pet
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
<<<<<<< HEAD
class Pet extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "a Pet",
=======
class Pet implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
>>>>>>> ooof
  "required" : [ "name", "photoUrls" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
<<<<<<< HEAD
      "format" : "int64"
=======
      "format" : "int64",
      "x-is-unique" : true
>>>>>>> ooof
    },
    "category" : {
      "$ref" : "#/components/schemas/Category"
    },
    "name" : {
      "type" : "string",
      "example" : "doggie"
    },
    "photoUrls" : {
      "type" : "array",
      "xml" : {
        "name" : "photoUrl",
        "wrapped" : true
      },
      "items" : {
        "type" : "string"
      }
    },
    "tags" : {
      "type" : "array",
      "xml" : {
        "name" : "tag",
        "wrapped" : true
      },
      "items" : {
        "$ref" : "#/components/schemas/Tag"
      }
    },
    "status" : {
      "type" : "string",
      "description" : "pet status in the store",
      "enum" : [ "available", "pending", "sold" ]
    }
  },
<<<<<<< HEAD
  "description" : "A pet for sale in the pet store",
=======
>>>>>>> ooof
  "xml" : {
    "name" : "Pet"
  }
}
SCHEMA;
<<<<<<< HEAD
=======

    /** @var int $id */
    private $id;

    /** @var \OpenAPIServer\Model\Category $category */
    private $category;

    /** @var string $name */
    private $name;

    /** @var string[] $photoUrls */
    private $photoUrls;

    /** @var \OpenAPIServer\Model\Tag[] $tags */
    private $tags;

    /** @var string $status pet status in the store*/
    private $status;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
>>>>>>> ooof
}
