# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import
<<<<<<< HEAD
import sys
import unittest

import petstore_api
from petstore_api.model.dog_all_of import DogAllOf
=======

import unittest

import petstore_api
>>>>>>> ooof


class TestDogAllOf(unittest.TestCase):
    """DogAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDogAllOf(self):
        """Test DogAllOf"""
        # FIXME: construct object with mandatory attributes with example values
<<<<<<< HEAD
        # model = DogAllOf()  # noqa: E501
=======
        # model = petstore_api.DogAllOf()  # noqa: E501
>>>>>>> ooof
        pass


if __name__ == '__main__':
    unittest.main()
