# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import
<<<<<<< HEAD
import sys
import unittest

import petstore_api
try:
    from petstore_api.model import complex_quadrilateral
except ImportError:
    complex_quadrilateral = sys.modules[
        'petstore_api.model.complex_quadrilateral']
try:
    from petstore_api.model import simple_quadrilateral
except ImportError:
    simple_quadrilateral = sys.modules[
        'petstore_api.model.simple_quadrilateral']
from petstore_api.model.quadrilateral import Quadrilateral
=======

import unittest

import petstore_api
>>>>>>> ooof


class TestQuadrilateral(unittest.TestCase):
    """Quadrilateral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuadrilateral(self):
        """Test Quadrilateral"""
<<<<<<< HEAD
        instance = Quadrilateral(shape_type="Quadrilateral", quadrilateral_type="ComplexQuadrilateral")
        assert isinstance(instance, complex_quadrilateral.ComplexQuadrilateral)
        instance = Quadrilateral(shape_type="Quadrilateral", quadrilateral_type="SimpleQuadrilateral")
        assert isinstance(instance, simple_quadrilateral.SimpleQuadrilateral)
=======
        complex_quadrilateral = petstore_api.Quadrilateral(shape_type="Quadrilateral", quadrilateral_type="ComplexQuadrilateral")
        assert isinstance(complex_quadrilateral, petstore_api.ComplexQuadrilateral)
        simple_quadrilateral = petstore_api.Quadrilateral(shape_type="Quadrilateral", quadrilateral_type="SimpleQuadrilateral")
        assert isinstance(simple_quadrilateral, petstore_api.SimpleQuadrilateral)
>>>>>>> ooof


if __name__ == '__main__':
    unittest.main()
