# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import
<<<<<<< HEAD
import sys
import unittest

import petstore_api
from petstore_api.model.outer_enum import OuterEnum
=======

import unittest

import petstore_api
>>>>>>> ooof


class TestOuterEnum(unittest.TestCase):
    """OuterEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOuterEnum(self):
        """Test OuterEnum"""
<<<<<<< HEAD
        # Since 'OuterEnum' is nullable, validate the null value can be assigned
        # to OuterEnum.
        inst = OuterEnum(None)
        self.assertIsNone(inst)

        inst = OuterEnum('approved')
        assert isinstance(inst, OuterEnum)

        with self.assertRaises(petstore_api.ApiValueError):
            OuterEnum('garbage')
=======
        # FIXME: construct object with mandatory attributes with example values
        # model = petstore_api.OuterEnum()  # noqa: E501
        pass
>>>>>>> ooof


if __name__ == '__main__':
    unittest.main()
