/**
* OpenAPI Petstore
* This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.OuterEnum
import org.openapitools.client.models.OuterEnumDefaultValue
import org.openapitools.client.models.OuterEnumInteger
import org.openapitools.client.models.OuterEnumIntegerDefaultValue

import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
<<<<<<< HEAD

/**
 * 
 * @param enumStringRequired 
 * @param enumString 
=======
/**
 * 
 * @param enumString 
 * @param enumStringRequired 
>>>>>>> ooof
 * @param enumInteger 
 * @param enumNumber 
 * @param outerEnum 
 * @param outerEnumInteger 
 * @param outerEnumDefaultValue 
 * @param outerEnumIntegerDefaultValue 
 */
@Serializable
data class EnumTest (
    @SerialName(value = "enum_string_required") @Required val enumStringRequired: EnumTest.EnumStringRequired,
    @SerialName(value = "enum_string") val enumString: EnumTest.EnumString? = null,
    @SerialName(value = "enum_integer") val enumInteger: EnumTest.EnumInteger? = null,
    @SerialName(value = "enum_number") val enumNumber: EnumTest.EnumNumber? = null,
    @SerialName(value = "outerEnum") val outerEnum: OuterEnum? = null,
    @SerialName(value = "outerEnumInteger") val outerEnumInteger: OuterEnumInteger? = null,
    @SerialName(value = "outerEnumDefaultValue") val outerEnumDefaultValue: OuterEnumDefaultValue? = null,
    @SerialName(value = "outerEnumIntegerDefaultValue") val outerEnumIntegerDefaultValue: OuterEnumIntegerDefaultValue? = null
<<<<<<< HEAD
) {

=======
) 


{
>>>>>>> ooof
    /**
    * 
    * Values: uPPER,lower,eMPTY
    */
<<<<<<< HEAD
    @Serializable(with = EnumStringRequired.Serializer::class)
    enum class EnumStringRequired(val value: kotlin.String){
=======
    @Serializable(with = EnumString.Serializer::class)
    enum class EnumString(val value: kotlin.String){
>>>>>>> ooof
        uPPER("UPPER"),
        lower("lower"),
        eMPTY("");

<<<<<<< HEAD
        object Serializer : CommonEnumSerializer<EnumStringRequired>("EnumStringRequired", values(), values().map { it.value.toString() }.toTypedArray())
=======
        object Serializer : CommonEnumSerializer<EnumString>("EnumString", values(), values().map { it.value.toString() }.toTypedArray())
>>>>>>> ooof
    }
    /**
    * 
    * Values: uPPER,lower,eMPTY
    */
<<<<<<< HEAD
    @Serializable(with = EnumString.Serializer::class)
    enum class EnumString(val value: kotlin.String){
=======
    @Serializable(with = EnumStringRequired.Serializer::class)
    enum class EnumStringRequired(val value: kotlin.String){
>>>>>>> ooof
        uPPER("UPPER"),
        lower("lower"),
        eMPTY("");

<<<<<<< HEAD
        object Serializer : CommonEnumSerializer<EnumString>("EnumString", values(), values().map { it.value.toString() }.toTypedArray())
=======
        object Serializer : CommonEnumSerializer<EnumStringRequired>("EnumStringRequired", values(), values().map { it.value.toString() }.toTypedArray())
>>>>>>> ooof
    }
    /**
    * 
    * Values: _1,minus1
    */
    @Serializable(with = EnumInteger.Serializer::class)
    enum class EnumInteger(val value: kotlin.Int){
        _1(1),
        minus1(-1);

        object Serializer : CommonEnumSerializer<EnumInteger>("EnumInteger", values(), values().map { it.value.toString() }.toTypedArray())
    }
    /**
    * 
    * Values: _1period1,minus1Period2
    */
    @Serializable(with = EnumNumber.Serializer::class)
    enum class EnumNumber(val value: kotlin.Double){
        _1period1(1.1),
        minus1Period2(-1.2);

        object Serializer : CommonEnumSerializer<EnumNumber>("EnumNumber", values(), values().map { it.value.toString() }.toTypedArray())
    }
}

