//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct Cat: Codable { 

=======
public struct Cat: Codable {
>>>>>>> ooof

    public var className: String
    public var color: String? = "red"
    public var declawed: Bool?

    public init(className: String, color: String?, declawed: Bool?) {
        self.className = className
        self.color = color
        self.declawed = declawed
    }

}
