//
// List.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct List: Codable { 

=======
public struct List: Codable {
>>>>>>> ooof

    public var _123list: String?

    public init(_123list: String?) {
        self._123list = _123list
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case _123list = "123-list"
    }

}
