// Models.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> Any
}

<<<<<<< HEAD
public enum ErrorResponse : Error {
    case error(Int, Data?, Error)
}

public enum DownloadException : Error {
=======
public enum ErrorResponse: Error {
    case error(Int, Data?, Error)
}

public enum DownloadException: Error {
>>>>>>> ooof
    case responseDataMissing
    case responseFailed
    case requestMissing
    case requestMissingPath
    case requestMissingURL
}

public enum DecodableRequestBuilderError: Error {
    case emptyDataResponse
    case nilHTTPResponse
    case unsuccessfulHTTPStatusCode
    case jsonDecoding(DecodingError)
    case generalError(Error)
}

<<<<<<< HEAD

=======
>>>>>>> ooof
open class Response<T> {
    public let statusCode: Int
    public let header: [String: String]
    public let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: HTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
<<<<<<< HEAD
        var header = [String:String]()
=======
        var header = [String: String]()
>>>>>>> ooof
        for (key, value) in rawHeader {
            if let key = key.base as? String, let value = value as? String {
                header[key] = value
            }
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}
