//
// AdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct AdditionalPropertiesClass: Codable { 


    public private(set) var mapString: [String:String]?
    public private(set) var mapMapString: [String:[String:String]]?

    public init(mapString: [String:String]?, mapMapString: [String:[String:String]]?) {
=======
public struct AdditionalPropertiesClass: Codable {

    public private(set) var mapString: [String: String]?
    public private(set) var mapMapString: [String: [String: String]]?

    public init(mapString: [String: String]?, mapMapString: [String: [String: String]]?) {
>>>>>>> ooof
        self.mapString = mapString
        self.mapMapString = mapMapString
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case mapString = "map_string"
        case mapMapString = "map_map_string"
    }

}
