//
// ApiResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct ApiResponse: Codable { 

=======
public struct ApiResponse: Codable {
>>>>>>> ooof

    public private(set) var code: Int?
    public private(set) var type: String?
    public private(set) var message: String?

    public init(code: Int?, type: String?, message: String?) {
        self.code = code
        self.type = type
        self.message = message
    }

}
