//
// ArrayOfNumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct ArrayOfNumberOnly: Codable { 

=======
public struct ArrayOfNumberOnly: Codable {
>>>>>>> ooof

    public private(set) var arrayNumber: [Double]?

    public init(arrayNumber: [Double]?) {
        self.arrayNumber = arrayNumber
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case arrayNumber = "ArrayNumber"
    }

}
