//
// ArrayOfArrayOfNumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct ArrayOfArrayOfNumberOnly: Codable { 

=======
public struct ArrayOfArrayOfNumberOnly: Codable {
>>>>>>> ooof

    public private(set) var arrayArrayNumber: [[Double]]?

    public init(arrayArrayNumber: [[Double]]?) {
        self.arrayArrayNumber = arrayArrayNumber
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case arrayArrayNumber = "ArrayArrayNumber"
    }

}
