//
// CatAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct CatAllOf: Codable { 

=======
public struct CatAllOf: Codable {
>>>>>>> ooof

    public private(set) var declawed: Bool?

    public init(declawed: Bool?) {
        self.declawed = declawed
    }

}
