//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct Category: Codable { 

=======
public struct Category: Codable {
>>>>>>> ooof

    public private(set) var id: Int64?
    public private(set) var name: String = "default-name"

    public init(id: Int64?, name: String) {
        self.id = id
        self.name = name
    }

}
