//
// HasOnlyReadOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct HasOnlyReadOnly: Codable { 

=======
public struct HasOnlyReadOnly: Codable {
>>>>>>> ooof

    public private(set) var bar: String?
    public private(set) var foo: String?

    public init(bar: String?, foo: String?) {
        self.bar = bar
        self.foo = foo
    }

}
