//
// Name.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing model name same as property name */
<<<<<<< HEAD
public struct Name: Codable { 

=======
public struct Name: Codable {
>>>>>>> ooof

    public private(set) var name: Int
    public private(set) var snakeCase: Int?
    public private(set) var property: String?
    public private(set) var _123number: Int?

    public init(name: Int, snakeCase: Int?, property: String?, _123number: Int?) {
        self.name = name
        self.snakeCase = snakeCase
        self.property = property
        self._123number = _123number
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case name
        case snakeCase = "snake_case"
        case property
        case _123number = "123Number"
    }

}
