//
// ReadOnlyFirst.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct ReadOnlyFirst: Codable { 

=======
public struct ReadOnlyFirst: Codable {
>>>>>>> ooof

    public private(set) var bar: String?
    public private(set) var baz: String?

    public init(bar: String?, baz: String?) {
        self.bar = bar
        self.baz = baz
    }

}
