//
// SpecialModelName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

<<<<<<< HEAD

public struct SpecialModelName: Codable { 

=======
public struct SpecialModelName: Codable {
>>>>>>> ooof

    public private(set) var specialPropertyName: Int64?

    public init(specialPropertyName: Int64?) {
        self.specialPropertyName = specialPropertyName
    }

<<<<<<< HEAD
    public enum CodingKeys: String, CodingKey, CaseIterable { 
=======
    public enum CodingKeys: String, CodingKey, CaseIterable {
>>>>>>> ooof
        case specialPropertyName = "$special[property.name]"
    }

}
